django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

django_project/quotes/urls.py
from django.urls import path

from . import views
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path("", views.main, name="index"),
    path("page/<int:page>/", views.main, name="index_paginate"),
    path("add/author/", views.add_author, name="add_author"),
    path("add/quote/", views.add_quote, name="add_quote"),
    path("author/<str:author_fullname>", views.about_author, name="about_author"),
    path("tag/<str:tag_name>/", views.show_quotes, name="show_quotes"),
    path("tag/<str:tag_name>/page/<int:page>/", views.show_quotes, name="show_quotes_paginate"),
]

django_project/users/urls.py
from django.urls import path, include

from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from . import views

app_name = "users"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),

    path("signup/", views.signup, name="signup"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

django_project/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self) -> str:
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Quote(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    quote = models.TextField()

    def __str__(self) -> str:
        return self.quote

django_project/users/models.py
from django.db import models

# Create your models here.

django_project/quotes/forms.py
from django import forms

from .models import Quote, Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(forms.ModelForm):
    author = forms.ModelChoiceField(queryset=Author.objects.all().order_by("fullname"))
    tags = forms.CharField(
        label='Tags',
        help_text='Enter tags separated by commas.'
    )

    class Meta:
        model = Quote
        fields = ['author', 'quote']

django_project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    email = forms.CharField(max_length=100,
                            required=True,
                            widget=forms.TextInput()),
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

django_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404

from .models import Quote, Tag, Author
from .forms import AuthorForm, QuoteForm

from .utils import get_mongodb

def get_top_5_tags():
    top_5_tags = Tag.objects.annotate(amount_quotes=Count("quote")).order_by("-amount_quotes")[:10]
    font_sizes = list(range(28, 9, -2))
    for i, tag in enumerate(top_5_tags):
        tag.font_size = font_sizes[i]
    return top_5_tags


def main(request, page=1):
    quotes = Quote.objects.all()
    top_5_tags = get_top_5_tags()

    per_page = 5
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    context = {"quotes": quotes_on_page, "top_tags": top_5_tags}
    return render(request, "quotes/index.html", context)


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quotes:index')
    else:
        form = AuthorForm()
    context = {'form': form}
    return render(request, 'quotes/add_author.html', context)


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            tags = form.cleaned_data['tags']
            tags = [tag.strip() for tag in tags.split(' ')]
            quote = form.save(commit=False)
            quote.author = form.cleaned_data['author']
            quote.save()

            for tag_text in tags:
                tag = Tag.objects.get_or_create(name=tag_text)[0]
                quote.tags.add(tag)
            return redirect("quotes:index")
    else:
        form = QuoteForm()

    context = {'form': form}
    return render(request, 'quotes/add_quote.html', context)


def about_author(request, author_fullname):
    author = get_object_or_404(Author, fullname=author_fullname)
    context = {'author': author}
    return render(request, 'quotes/about_author.html', context)


def show_quotes(request, tag_name, page=1):
    quotes = Quote.objects.filter(tags__name=tag_name)

    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    context = {"quotes": quotes_on_page, "tag": tag_name}
    return render(request, "quotes/show_quotes.html", context)

django_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm

from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy

from .forms import RegisterForm



def signup(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save(commit=True)
            login(request, new_user)
            return redirect("quotes:index")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "users/signup.html", context={"form": RegisterForm()})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

django_project/quotes/templates/quotes/about_author.html
{% extends "quotes/base.html" %}
{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Author: {{ author.fullname }}</h1>
    <p><strong>Born date:</strong> {{ author.born_date }}</p>
    <p><strong>Born location:</strong> {{ author.born_location }}</p>
    <p class="mt-3"><strong>Description:</strong></p>
    <p>{{ author.description }}</p>
</div>
{% endblock content %}

django_project/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-center">
                    <h3 class="card-title">Create Author</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.fullname.id_for_label }}">Full Name:</label>
                            {{ form.fullname }}
                        </div>
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.born_date.id_for_label }}">Born Date:</label>
                            {{ form.born_date }}
                        </div>
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.born_location.id_for_label }}">Born Location:</label>
                            {{ form.born_location }}
                        </div>
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.description.id_for_label }}">Description:</label>
                            {{ form.description }}
                        </div>
                        <div class="text-center my-3">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_project/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-center">
                    <h3 class="card-title">Create Quote</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.author.id_for_label }}">Author:</label>
                            {{ form.author }}
                        </div>
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.quote.id_for_label }}">Quote:</label>
                            {{ form.quote }}
                        </div>
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.tags_text.id_for_label }}">Tags:</label>
                            {{ form.tags }}
                        </div>
                        <div class="text-center my-3">
                            <button type="submit" class="btn btn-primary">Create</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user_scale=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Quotes</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4 text-end">
            {% if not user.is_authenticated %}
            <a href="/users/login" class="btn btn-primary">Login</a>
            <a href="/users/signup" class="btn btn-primary">Sign Up</a>
            {% else %}
            <a href="/users/logout" class="btn btn-light"
               title='Username: "{{ user }}"'>Logout</a>
            <a href="/add/author" class="btn btn-info">Add author</a>
            <a href="/add/quote" class="btn btn-info">Add quote</a>
            <p class="p-2 g-col-6 pt-3">Hello, {{ user.username }}! 👋🏻</p>
            {% endif %}
        </div>
    </div>

    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

django_project/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}
{% load extract %}
{% block content %}
<div class="row">
    <div class="col-md">
        {% for quote in quotes %}
         <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
             <span class="text" itemprop="text">
                 {{quote.quote}}
             </span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="/author/{{ quote.author }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <nav>
        <ul class="pagination d-flex justify-content-between">
            <li class="page-item">
                <a href="{% if quotes.has_previous %} {% url 'quotes:index_paginate' quotes.previous_page_number %} {% endif %}"
                class="btn-previous page-link {% if not quotes.has_previous %} disabled {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="page-item">
                <a href="{% if quotes.has_next %} {% url 'quotes:index_paginate' quotes.next_page_number %} {% endif %}"
                class="btn-next page-link {% if not quotes.has_next %} disabled {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
    </nav>
    </div>
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <span class="tag-item">
            <a class="tag" style="font-size: {{tag.font_size}}px" href="/tag/{{tag.name}}">{{tag.name}}</a>
        </span>
        {% endfor %}
    </div>
</div>
{% endblock content %}

django_project/quotes/templates/quotes/show_quotes.html
{% extends "quotes/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <h3>Viewing tag: <a href="/tag/{{ tag }}">{{ tag }}</a></h3>
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">{{ quote.quote }}</span>
        <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
        <a href="/author/{{ quote.author.fullname }}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pagination d-flex justify-content-between">
            <li class="page-item">
                <a href="{% if quotes.has_previous %} {% url 'quotes:show_quotes_paginate' tag_name=tag page=quotes.previous_page_number %} {% endif %}"
                class="page-link {% if not quotes.has_previous %} hidden {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="page-item">
                <a href="{% if quotes.has_next %} {% url 'quotes:show_quotes_paginate' tag_name=tag page=quotes.next_page_number %} {% endif %}"
                class="page-link {% if not quotes.has_next %} hidden {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
    </nav>
    </div>
</div>
{% endblock content %}

django_project/quotes/templates/quotes/tag.html
{% load extract%}
{% block content %}
<div class="row">
    <div class="col-md">
        {% for quote in quotes %}
         <div class="quote" itemscope="" itemtype="http://schema.org/CreateveWork">
             <span class="text" itemprop="text">
                 {{quote.quote}}
             </span>
            <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                <a href="/author/{{ quote.author }}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{ tag }}">{{ tag }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <nav>
        <ul class="pagination d-flex justify-content-between">
            <li class="page-item">
                <a href="{% if quotes.has_previous %} {% url 'quotes:index_paginate' quotes.previous_page_number %} {% endif %}"
                class="page-link {% if not quotes.has_previous %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="page-item">
                <a href="{% if quotes.has_next %} {% url 'quotes:index_paginate' quotes.next_page_number %} {% endif %}"
                class="page-link {% if not quotes.has_next %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
    </nav>
    </div>
    <div class="col-md-4 tags-box">

        <h2>Top Ten tags</h2>
        {% for tag in top_tags %}
        <span class="tag-item">
            <a class="tag" style="font-size: {{tag.font_size}}px" href="/tag/{{tag.name}}">{{tag.name}}</a>
        </span>
        {% endfor %}

    </div>
</div>
{% endblock content %}

django_project/users/templates/users/login.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-center">
                    <h3 class="card-title">Login</h3>
                </div>
                <div class="card-body d-flex align-items-center justify-content-center">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.username.id_for_label }}">Username:</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group my-3 d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.password.id_for_label }}">Password:</label>
                            {{ form.password }}
                        </div>
                        <div class="text-center my-3">
                            <button type="submit" class="btn btn-success">Login</button>
                            <button class="btn btn-secondary" type="reset ">Reset</button>
                        </div>
                        <div class="small text-center">
                            <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
                        </div>
                        <input type="hidden" name="next" value="{% url 'quotes:index' %}"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_project/users/templates/users/password_reset.html
{% extends "quotes/base.html" %}


{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
    
    input {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
    <h2>Password reset</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
         <button type="submit" class="btn btn-primary">Request password reset</button>
        </div>

    </form>
</div>

{% endblock %}

django_project/users/templates/users/password_reset_complete.html
{% extends "quotes/base.html" %}


{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
    
    input {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
    <h2>Password reset</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
         <button type="submit" class="btn btn-primary">Request password reset</button>
        </div>

    </form>
</div>

{% endblock %}

django_project/users/templates/users/password_reset_confirm.html
{% extends "quotes/base.html" %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% block content %}
<style>
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    label {
        width: 100%;
    }
    
    input {
        width: 100%;
    }
</style>
<div class="form-signin rounded-3 bg-light">
<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="text-center">
        <button type="submit" class="btn btn-primary">Save new password</button>
    </div>
</form>
</div>

{% endblock %}

django_project/users/templates/users/password_reset_done.html
{% extends "quotes/base.html" %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

django_project/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

django_project/users/templates/users/signup.html
{% extends "quotes/base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header d-flex align-items-center justify-content-center">
                    <h3 class="card-title">Registration</h3>
                </div>
                <div class="card-body d-flex align-items-center justify-content-center">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.username.id_for_label }}">Username:</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group my-3 d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.email.id_for_label }}">Email:</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group my-3 d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.password.id_for_label }}">Password:</label>
                            {{ form.password1 }}
                        </div>
                        <div class="form-group my-3 d-flex flex-column align-items-center justify-content-center">
                            <label for="{{ form.password2.id_for_label }}">Confirm password:</label>
                            {{ form.password2 }}
                        </div>
                        <span>{{ form.errors.password2 }}</span>
                        <div class="text-center my-3">
                            <button type="submit" class="btn btn-success">Sign Up</button>
                            <button class="btn btn-secondary" type="reset ">Reset</button>
                        </div>
                        <input type="hidden" name="next" value="{% url 'quotes:index' %}"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}